import React,{useEffect,useState} from 'react'
import {Alert,Avatar,Box,Button,Card,Chip,CircularProgress,Dialog,DialogActions,DialogContent,DialogTitle,Divider,FormControl,IconButton,InputAdornment,InputLabel,MenuItem,Radio,Select,Switch,Tab,Tabs,TextField,Tooltip,Typography} from '@mui/material'
import {Add,AutoAwesome,BlockOutlined,CheckCircle,CloudDownload,CloudUpload,DeleteOutline,Description,GroupOutlined,Key,OpenInNew,Person,PsychologyOutlined,SettingsSuggestOutlined,StorageOutlined,ThumbUpOutlined,Visibility,VisibilityOff} from '@mui/icons-material'
import {api,errorMessage} from '../api'

const sectors=['Presidência','Diretoria Administrativa e Financeira','Diretoria Técnica','Tecnologia da Informação','Recursos Humanos','Licitações e Contratos','Jurídico','Outro']
const roles={padrao:'Padrão',diretor:'Diretor',gerente:'Gerente de TI',admin:'Administrador'}
const validPassword=value=>value.length>=8&&/[A-Z]/.test(value)&&/[a-z]/.test(value)&&/\d/.test(value)&&/[^A-Za-z0-9]/.test(value)
const modelTypes=['RILC SOPH','Modelo de ETP','Modelo de Termo de Referência','Modelo de Despacho','Modelo de Memorando','Lei ou Regulamento','Manual Institucional','Outro Modelo']
const titleCase=value=>String(value||'').toLocaleLowerCase('pt-BR').replace(/(^|[\s/_-])([a-záéíóúâêôãõç])/g,(_,space,letter)=>space+letter.toLocaleUpperCase('pt-BR')).replace(/\b(rilc|soph|etp|tr|sei|pdf|docx)\b/gi,word=>word.toUpperCase())

export default function Admin({currentUser}){
 const [users,setUsers]=useState([]),[dialog,setDialog]=useState(null),[error,setError]=useState(''),[form,setForm]=useState({name:'',email:'',sector:'',role:'padrao',password:'',confirm:''})
 const [sectorOptions,setSectorOptions]=useState([])
 const [adminTab,setAdminTab]=useState(currentUser.role==='admin'?0:2)
 const [models,setModels]=useState([]),[modelFiles,setModelFiles]=useState([]),[modelType,setModelType]=useState('RILC SOPH'),[modelTitle,setModelTitle]=useState(''),[uploading,setUploading]=useState(false),[modelMessage,setModelMessage]=useState(''),[knowledgeTab,setKnowledgeTab]=useState(0),[selectedModel,setSelectedModel]=useState(null)
 const [learningExamples,setLearningExamples]=useState([]),[learningFilter,setLearningFilter]=useState('pendente'),[learningBusy,setLearningBusy]=useState(null)
 const [aiConfig,setAiConfig]=useState({provider:'gemini',enabled:false,model:'gemini-3.6-flash',api_key:'',configured:false,masked_api_key:'',organization_id:'',project_id:''}),[showApiKey,setShowApiKey]=useState(false),[aiBusy,setAiBusy]=useState(false),[aiTesting,setAiTesting]=useState(false),[aiMessage,setAiMessage]=useState(null)
 const isAdmin=currentUser.role==='admin'
 const refresh=()=>api.get('/users').then(r=>setUsers(r.data)).catch(e=>setError(errorMessage(e,'Não foi possível carregar os usuários.')))
 const refreshSectors=()=>api.get('/sectors').then(r=>setSectorOptions(r.data)).catch(()=>setSectorOptions([]))
 const refreshModels=()=>api.get('/knowledge').then(r=>setModels(r.data)).catch(()=>setModels([]))
 const refreshAI=()=>api.get('/admin/ai').then(({data})=>setAiConfig(current=>({...current,...data,api_key:''}))).catch(()=>{})
 const refreshLearning=()=>api.get('/admin/learning').then(r=>setLearningExamples(r.data)).catch(()=>setLearningExamples([]))
 useEffect(()=>{refresh();refreshSectors();if(isAdmin){refreshModels();refreshAI();refreshLearning()}},[])
 const update=async(id,changes)=>{setError('');try{await api.patch(`/users/${id}`,changes);await refresh()}catch(e){setError(errorMessage(e,'Não foi possível atualizar o usuário.'))}}
 const remove=async id=>{setError('');try{await api.delete(`/users/${id}`);await refresh()}catch(e){setError(errorMessage(e,'Não foi possível desativar o usuário.'))}}
 const create=async e=>{e.preventDefault();setError('');if(!/@sophi?a?\.ro\.gov\.br$/i.test(form.email)){setError('Informe um e-mail institucional da SOPH.');return}if(!validPassword(form.password)){setError('A senha deve ter 8 caracteres, maiúscula, minúscula, número e símbolo.');return}if(form.password!==form.confirm){setError('A confirmação de senha não corresponde.');return}const sector=sectorOptions.find(item=>item.name===form.sector);if(!sector){setError('Selecione um setor válido.');return}try{await api.post('/users',{name:form.name,email:form.email,password:form.password,role:form.role,sector_id:sector.id});setDialog(null);setForm({name:'',email:'',sector:'',role:'padrao',password:'',confirm:''});await refresh()}catch(e){setError(errorMessage(e,'Não foi possível criar o usuário.'))}}
 const changePassword=async e=>{e.preventDefault();setError('');if(!validPassword(form.password)){setError('A senha deve ter 8 caracteres, maiúscula, minúscula, número e símbolo.');return}if(form.password!==form.confirm){setError('A confirmação não corresponde.');return}try{await api.put(`/users/${dialog.id}/password`,{password:form.password});setDialog(null);setForm({...form,password:'',confirm:''})}catch(e){setError(errorMessage(e,'Não foi possível alterar a senha.'))}}
 const uploadModels=async e=>{e.preventDefault();if(!modelFiles.length||modelType==='Outro Modelo'&&!modelTitle.trim())return;setUploading(true);setModelMessage('');try{for(const file of modelFiles){const data=new FormData();data.append('title',modelTitle.trim()||file.name.replace(/\.(pdf|docx)$/i,''));data.append('category',modelType);data.append('file',file);await api.post('/knowledge/upload',data)}setModelMessage(`${modelFiles.length} documento(s) integrado(s) à base institucional.`);setModelFiles([]);setModelTitle('');refreshModels()}catch(e){setModelMessage(errorMessage(e,'Não foi possível integrar os modelos.'))}finally{setUploading(false)}}
 const modelBlob=async model=>{try{return (await api.get(`/knowledge/${model.id}/file`,{responseType:'blob'})).data}catch{return new Blob([model.content||'Conteúdo não disponível.'],{type:'text/plain;charset=utf-8'})}}
 const viewModel=async model=>{const preview=window.open('about:blank','_blank');const blob=await modelBlob(model),url=URL.createObjectURL(blob);if(preview)preview.location.href=url;setTimeout(()=>URL.revokeObjectURL(url),60000)}
 const downloadModel=async model=>{const blob=await modelBlob(model),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=model.filename||`${model.title}.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const saveAI=async()=>{setAiBusy(true);setAiMessage(null);try{const payload={provider:aiConfig.provider,enabled:aiConfig.enabled,model:aiConfig.model,organization_id:aiConfig.organization_id||'',project_id:aiConfig.project_id||'',...(aiConfig.api_key.trim()?{api_key:aiConfig.api_key.trim()}:{})};const{data}=await api.put('/admin/ai',payload);setAiConfig(current=>({...current,...data,api_key:''}));setAiMessage({severity:'success',text:payload.provider==='gemini'&&payload.enabled?'Gemini salvo como padrão institucional. A mesma chave será usada automaticamente por todos os usuários.':'Configuração de inteligência artificial salva com segurança.'})}catch(e){setAiMessage({severity:'error',text:errorMessage(e,'Não foi possível salvar a configuração.')})}finally{setAiBusy(false)}}
 const testAI=async()=>{setAiTesting(true);setAiMessage(null);try{const payload={provider:aiConfig.provider,model:aiConfig.model,organization_id:aiConfig.organization_id||'',project_id:aiConfig.project_id||'',...(aiConfig.api_key.trim()?{api_key:aiConfig.api_key.trim()}:{})};const{data}=await api.post('/admin/ai/test',payload);setAiMessage({severity:'success',text:data.message})}catch(e){setAiMessage({severity:'error',text:errorMessage(e,`Não foi possível conectar à ${aiConfig.provider==='openai'?'OpenAI':'Gemini'}.`)})}finally{setAiTesting(false)}}
 const reviewLearning=async(id,status)=>{setLearningBusy(id);try{await api.patch(`/admin/learning/${id}`,{status});await refreshLearning()}catch(e){setError(errorMessage(e,'Não foi possível atualizar o aprendizado.'))}finally{setLearningBusy(null)}}
 return <Box maxWidth={1120} mx="auto" pb={4}>
  <Box display="flex" justifyContent="space-between" alignItems={{xs:'flex-start',sm:'center'}} gap={2} mb={2.5} flexDirection={{xs:'column',sm:'row'}}><Box><Typography variant="h4" fontWeight={850}>Administração</Typography><Typography color="text.secondary" variant="body2">Configurações institucionais da SOPH.IA</Typography></Box><Chip size="small" color={isAdmin?'primary':'default'} label={isAdmin?'Administrador':'Gerente de TI'}/></Box>
  <Card sx={{mb:2.5,p:.5,borderRadius:3}}>
   <Tabs value={adminTab} onChange={(_,value)=>setAdminTab(value)} variant="scrollable" scrollButtons="auto" sx={{minHeight:46,'& .MuiTab-root':{minHeight:46,textTransform:'none',fontWeight:750,borderRadius:2,px:2},'& .Mui-selected':{bgcolor:'action.selected'}}}>
    {isAdmin&&<Tab icon={<SettingsSuggestOutlined fontSize="small"/>} iconPosition="start" label="Inteligência artificial" value={0}/>}
    {isAdmin&&<Tab icon={<StorageOutlined fontSize="small"/>} iconPosition="start" label="Base institucional" value={1}/>}
    <Tab icon={<GroupOutlined fontSize="small"/>} iconPosition="start" label="Usuários" value={2}/>
    {isAdmin&&<Tab icon={<PsychologyOutlined fontSize="small"/>} iconPosition="start" label="Aprendizado" value={3}/>}
   </Tabs>
  </Card>
  {isAdmin&&adminTab===0&&<Card sx={{p:{xs:2,md:2.5},mb:2.5,borderColor:aiConfig.enabled?'primary.main':'divider',borderRadius:3,background:theme=>theme.palette.mode==='dark'?'linear-gradient(135deg,rgba(242,101,34,.09),rgba(255,255,255,.02))':'linear-gradient(135deg,rgba(242,101,34,.08),rgba(255,255,255,.92))'}}>
   <Box display="flex" justifyContent="space-between" alignItems="flex-start" gap={2} mb={3}><Box display="flex" gap={1.5}><Avatar sx={{bgcolor:'primary.main',color:'#fff'}}><AutoAwesome/></Avatar><Box><Box display="flex" alignItems="center" gap={1} flexWrap="wrap"><Typography variant="h5" fontWeight={850}>Inteligência Artificial</Typography>{aiConfig.configured&&<Chip icon={<CheckCircle/>} color="success" size="small" label="Chave configurada"/>}</Box><Typography color="text.secondary">Conecte a SOPH.IA ao Gemini para elaborar, analisar e revisar documentos.</Typography></Box></Box><Box display="flex" alignItems="center" gap={1}><Typography fontWeight={700}>{aiConfig.enabled?'Ativado':'Desativado'}</Typography><Switch color="primary" checked={aiConfig.enabled} onChange={e=>setAiConfig({...aiConfig,enabled:e.target.checked})}/></Box></Box>
   <Box display="grid" gridTemplateColumns={{xs:'1fr',md:'220px 1fr'}} gap={2}>
    <FormControl fullWidth><InputLabel>Provedor de IA</InputLabel><Select label="Provedor de IA" value={aiConfig.provider} onChange={e=>{const provider=e.target.value;setAiConfig({...aiConfig,provider,model:provider==='openai'?'gpt-5.6-sol':provider==='gemini'?'gemini-3.6-flash':aiConfig.model,api_key:'',configured:false,masked_api_key:'',organization_id:'',project_id:''});setAiMessage(null)}}><MenuItem value="gemini">Google Gemini</MenuItem><MenuItem value="openai">OpenAI</MenuItem><MenuItem value="ollama">Ollama local</MenuItem><MenuItem value="template">Modo interno básico</MenuItem></Select></FormControl>
    <FormControl fullWidth disabled={!['gemini','openai'].includes(aiConfig.provider)}><InputLabel>Modelo</InputLabel><Select label="Modelo" value={aiConfig.model} onChange={e=>setAiConfig({...aiConfig,model:e.target.value})}>{aiConfig.provider==='gemini'&&<MenuItem value="gemini-3.6-flash"><Box><Typography fontWeight={750}>Gemini 3.6 Flash</Typography><Typography variant="caption" color="text.secondary">Modelo estável para texto, documentos e PDFs extensos</Typography></Box></MenuItem>}{aiConfig.provider==='openai'&&[<MenuItem key="sol" value="gpt-5.6-sol"><Box><Typography fontWeight={750}>GPT-5.6 Sol</Typography><Typography variant="caption" color="text.secondary">Máxima qualidade para documentos complexos</Typography></Box></MenuItem>,<MenuItem key="terra" value="gpt-5.6-terra"><Box><Typography fontWeight={750}>GPT-5.6 Terra</Typography><Typography variant="caption" color="text.secondary">Equilíbrio entre qualidade e custo</Typography></Box></MenuItem>,<MenuItem key="luna" value="gpt-5.6-luna"><Box><Typography fontWeight={750}>GPT-5.6 Luna</Typography><Typography variant="caption" color="text.secondary">Menor custo para alto volume</Typography></Box></MenuItem>]}</Select></FormControl>
   </Box>
   {aiConfig.provider==='gemini'&&<Box mt={2}>
    <TextField fullWidth type={showApiKey?'text':'password'} label={aiConfig.configured?'Nova chave API do Gemini (opcional)':'Chave API do Gemini'} placeholder={aiConfig.configured?aiConfig.masked_api_key:'Cole aqui a chave criada no Google AI Studio'} value={aiConfig.api_key} onChange={e=>setAiConfig({...aiConfig,api_key:e.target.value})} helperText={aiConfig.configured?'A chave atual continuará ativa se este campo permanecer vazio.':'A chave é enviada somente ao backend e armazenada de forma protegida.'} InputProps={{endAdornment:<InputAdornment position="end"><IconButton onClick={()=>setShowApiKey(value=>!value)} edge="end" aria-label={showApiKey?'Ocultar chave':'Mostrar chave'}>{showApiKey?<VisibilityOff/>:<Visibility/>}</IconButton></InputAdornment>}}/>
    <Box mt={2} px={1.5} py={1.25} display="flex" alignItems="center" justifyContent="space-between" gap={2} border="1px solid" borderColor={aiConfig.enabled?'primary.main':'divider'} borderRadius={2.5} bgcolor={aiConfig.enabled?'action.selected':'transparent'}>
     <Box><Box display="flex" alignItems="center" gap={1} flexWrap="wrap"><Typography fontWeight={800}>Gemini como padrão institucional</Typography>{aiConfig.enabled&&aiConfig.configured&&<Chip size="small" color="success" label="Padrão ativo"/>}</Box><Typography variant="body2" color="text.secondary">Guarda a chave de forma protegida e a utiliza automaticamente nos chats de todos os usuários.</Typography></Box>
     <Switch checked={aiConfig.enabled} onChange={e=>setAiConfig({...aiConfig,enabled:e.target.checked})} inputProps={{'aria-label':'Usar Gemini como padrão institucional'}}/>
    </Box>
    <Alert severity="info" sx={{mt:2}}>Use uma chave de um projeto institucional com faturamento e limites configurados. Documentos enviados ao Gemini são processados externamente; não envie conteúdo sigiloso sem autorização.</Alert>
   </Box>}
   {aiConfig.provider==='openai'&&<Box mt={2} display="grid" gap={2}>
    <TextField fullWidth type={showApiKey?'text':'password'} label={aiConfig.configured?'Nova chave API da OpenAI (opcional)':'Chave API da OpenAI'} placeholder={aiConfig.configured?aiConfig.masked_api_key:'Cole aqui a chave criada na plataforma OpenAI'} value={aiConfig.api_key} onChange={e=>setAiConfig({...aiConfig,api_key:e.target.value})} helperText={aiConfig.configured?'A chave atual continuará ativa se este campo permanecer vazio.':'A chave é enviada somente ao backend e armazenada de forma protegida.'} InputProps={{endAdornment:<InputAdornment position="end"><IconButton onClick={()=>setShowApiKey(value=>!value)} edge="end" aria-label={showApiKey?'Ocultar chave':'Mostrar chave'}>{showApiKey?<VisibilityOff/>:<Visibility/>}</IconButton></InputAdornment>}}/>
    <Box display="grid" gridTemplateColumns={{xs:'1fr',md:'1fr 1fr'}} gap={2}><TextField label="ID da organização (opcional)" placeholder="org-..." value={aiConfig.organization_id||''} onChange={e=>setAiConfig({...aiConfig,organization_id:e.target.value})}/><TextField label="ID do projeto (opcional)" placeholder="proj_..." value={aiConfig.project_id||''} onChange={e=>setAiConfig({...aiConfig,project_id:e.target.value})}/></Box>
    <Alert severity="info">Use uma chave de projeto com faturamento e permissão para o modelo selecionado. A SOPH.IA utiliza a Responses API e não expõe a chave ao navegador.</Alert>
   </Box>}
   {aiConfig.provider==='ollama'&&<Alert severity="info" sx={{mt:2}}>O Ollama utiliza a configuração local do servidor e mantém os documentos dentro da infraestrutura da SOPH.</Alert>}
   {aiMessage&&<Alert severity={aiMessage.severity} onClose={()=>setAiMessage(null)} sx={{mt:2}}>{aiMessage.text}</Alert>}
   <Divider sx={{my:2.5}}/>
   <Box display="flex" justifyContent="flex-end" gap={1} flexWrap="wrap">{['gemini','openai'].includes(aiConfig.provider)&&<Button variant="outlined" disabled={aiTesting||(!aiConfig.configured&&!aiConfig.api_key.trim())} onClick={testAI} startIcon={aiTesting?<CircularProgress size={17}/>:<CheckCircle/>}>{aiTesting?'Testando...':'Testar conexão'}</Button>}<Button variant="contained" disabled={aiBusy} onClick={saveAI} startIcon={aiBusy?<CircularProgress color="inherit" size={17}/>:<AutoAwesome/>}>{aiBusy?'Salvando...':'Salvar configuração'}</Button></Box>
  </Card>}
  {isAdmin&&adminTab===1&&<Card sx={{p:{xs:2,md:2.5},mb:2.5,borderColor:'primary.main',borderRadius:3}}><Box display="flex" alignItems="center" gap={1.5} mb={.5}><CloudUpload color="primary"/><Typography variant="h5" fontWeight={850}>Modelos e normativos institucionais</Typography></Box><Typography color="text.secondary" variant="body2" mb={2}>Documentos oficiais consultados pela SOPH.IA para elaborar e revisar minutas.</Typography>
   <Tabs value={knowledgeTab} onChange={(_,value)=>setKnowledgeTab(value)} sx={{mb:2,borderBottom:'1px solid',borderColor:'divider'}}><Tab label="Integrar Documentos"/><Tab label={`Documentos Integrados (${models.length})`}/></Tabs>
   {knowledgeTab===0&&<><Box component="form" onSubmit={uploadModels} display="grid" gridTemplateColumns="210px 1fr auto" gap={2} alignItems="start"><FormControl><InputLabel>Tipo Documental</InputLabel><Select label="Tipo Documental" value={modelType} onChange={e=>{setModelType(e.target.value);if(e.target.value!=='Outro Modelo')setModelTitle('')}} MenuProps={{PaperProps:{sx:{maxHeight:260,overflowY:'auto'}}}}>{modelTypes.map(type=><MenuItem key={type} value={type}>{type}</MenuItem>)}</Select></FormControl><Box display="grid" gap={1}>{modelType==='Outro Modelo'&&<TextField required label="Nome do Documento" placeholder="Ex.: Modelo de Relatório Técnico" value={modelTitle} onChange={e=>setModelTitle(e.target.value)}/>}<Button component="label" variant="outlined" startIcon={<Description/>} sx={{height:56}}>{modelFiles.length?`${modelFiles.length} Arquivo(s) Selecionado(s)`:'Selecionar PDF/DOCX'}<input hidden multiple type="file" accept=".pdf,.docx" onChange={e=>setModelFiles([...e.target.files])}/></Button></Box><Button type="submit" variant="contained" disabled={!modelFiles.length||uploading||modelType==='Outro Modelo'&&!modelTitle.trim()} sx={{height:56}}>{uploading?'Integrando...':'Integrar Modelos'}</Button></Box>
   {modelMessage&&<Alert severity={modelMessage.includes('integrado')?'success':'error'} sx={{mt:2}}>{modelMessage}</Alert>}
   {!!modelFiles.length&&<Box display="flex" flexWrap="wrap" gap={.7} mt={2}>{modelFiles.map((file,index)=><Chip key={`${file.name}-${index}`} label={titleCase(file.name.replace(/\.(pdf|docx)$/i,''))} onDelete={()=>setModelFiles(old=>old.filter((_,i)=>i!==index))}/>)}</Box>}</>}
   {knowledgeTab===1&&<Box><Typography color="text.secondary" mb={2}>Selecione um documento para visualizar ou baixar o arquivo original.</Typography><Box sx={{maxHeight:330,overflowY:'auto',border:'1px solid',borderColor:'divider',borderRadius:2}}>{models.map(model=><Box key={model.id} onClick={()=>setSelectedModel(model.id)} sx={{display:'grid',gridTemplateColumns:'auto minmax(0,1fr) auto',alignItems:'center',gap:1.2,p:1.4,borderBottom:'1px solid',borderColor:'divider',cursor:'pointer','&:last-child':{borderBottom:0},'&:hover':{bgcolor:'action.hover'},bgcolor:selectedModel===model.id?'action.selected':'transparent'}}><Radio size="small" checked={selectedModel===model.id}/><Box minWidth={0}><Typography fontWeight={750} noWrap>{titleCase(model.title)}</Typography><Typography variant="caption" color="text.secondary">{titleCase(model.category)} · {model.filename?.split('.').pop()?.toUpperCase()||'DOCUMENTO'}</Typography></Box><Description color="action"/></Box>)}{!models.length&&<Typography color="text.secondary" p={3} textAlign="center">Nenhum documento institucional cadastrado.</Typography>}</Box><Divider sx={{my:2}}/><Box display="flex" justifyContent="flex-end" gap={1}><Button variant="outlined" startIcon={<OpenInNew/>} disabled={!selectedModel} onClick={()=>viewModel(models.find(model=>model.id===selectedModel))}>Visualizar em Nova Aba</Button><Button variant="contained" startIcon={<CloudDownload/>} disabled={!selectedModel} onClick={()=>downloadModel(models.find(model=>model.id===selectedModel))}>Baixar Arquivo</Button></Box></Box>}
  </Card>}
  {isAdmin&&adminTab===3&&<Card sx={{p:{xs:2,md:2.5},mb:2.5,borderRadius:3}}>
   <Box display="flex" justifyContent="space-between" alignItems={{xs:'flex-start',sm:'center'}} gap={2} flexDirection={{xs:'column',sm:'row'}} mb={2}><Box display="flex" gap={1.5}><Avatar sx={{bgcolor:'primary.main',color:'#fff'}}><PsychologyOutlined/></Avatar><Box><Typography variant="h5" fontWeight={850}>Aprendizado institucional</Typography><Typography color="text.secondary" variant="body2">Revise exemplos coletados das conversas antes que orientem respostas futuras.</Typography></Box></Box><Chip color="primary" label={`${learningExamples.filter(item=>item.status==='aprovado').length} aprovados`}/></Box>
   <Alert severity="info" sx={{mb:2}}>Por segurança, pedidos e respostas ficam pendentes. Somente exemplos corretos, sem dados pessoais ou sigilosos, devem ser aprovados.</Alert>
   <Box display="flex" gap={1} mb={2} flexWrap="wrap">{['pendente','aprovado','rejeitado'].map(status=><Chip key={status} clickable color={learningFilter===status?'primary':'default'} variant={learningFilter===status?'filled':'outlined'} onClick={()=>setLearningFilter(status)} label={`${status.charAt(0).toUpperCase()+status.slice(1)} (${learningExamples.filter(item=>item.status===status).length})`}/>)}</Box>
   <Box display="grid" gap={1.2} maxHeight="58vh" overflow="auto" pr={.5}>{learningExamples.filter(item=>item.status===learningFilter).map(example=><Card key={example.id} variant="outlined" sx={{p:1.5,borderRadius:2.5}}><Box display="flex" justifyContent="space-between" gap={2}><Box minWidth={0}><Typography variant="caption" color="text.secondary">{example.user_name} · conversa {example.conversation_id}</Typography><Typography fontWeight={800} mt={.4}>{example.prompt.slice(0,260)}{example.prompt.length>260?'…':''}</Typography><Typography variant="body2" color="text.secondary" mt={.7} sx={{whiteSpace:'pre-line'}}>{example.response.slice(0,520)}{example.response.length>520?'…':''}</Typography></Box><Box display="flex" alignItems="flex-start" gap={.5}>{example.status!=='aprovado'&&<Tooltip title="Aprovar como referência institucional"><span><IconButton color="success" disabled={learningBusy===example.id} onClick={()=>reviewLearning(example.id,'aprovado')}><ThumbUpOutlined/></IconButton></span></Tooltip>}{example.status!=='rejeitado'&&<Tooltip title="Rejeitar exemplo"><span><IconButton color="error" disabled={learningBusy===example.id} onClick={()=>reviewLearning(example.id,'rejeitado')}><BlockOutlined/></IconButton></span></Tooltip>}</Box></Box></Card>)}{!learningExamples.some(item=>item.status===learningFilter)&&<Typography color="text.secondary" textAlign="center" py={5}>Nenhum exemplo nesta categoria.</Typography>}</Box>
  </Card>}
  {error&&<Alert severity="error" onClose={()=>setError('')} sx={{mb:2}}>{error}</Alert>}
  <Box sx={{display:adminTab===2?'block':'none'}}>
  <Box display="flex" justifyContent="space-between" alignItems="center" mb={1.5}><Box><Typography variant="h5" fontWeight={820}>Usuários</Typography><Typography color="text.secondary" variant="body2">{users.filter(u=>u.active).length} ativos · {users.length} cadastrados</Typography></Box><Button variant="contained" size="small" startIcon={<Add/>} onClick={()=>{setError('');setDialog({type:'new'})}}>Novo usuário</Button></Box>
  <Box display="grid" gap={1}>{users.map(user=><Card key={user.id} sx={{p:1.4,display:'grid',gridTemplateColumns:{xs:'auto minmax(0,1fr) auto',md:'auto minmax(220px,1fr) 160px 145px auto auto'},alignItems:'center',gap:{xs:1,md:1.25},borderRadius:2.5}}>
   <Avatar sx={{bgcolor:user.role==='admin'?'primary.main':user.role==='diretor'?'secondary.main':'action.selected'}}>{user.name?.[0]?.toUpperCase()||<Person/>}</Avatar>
   <Box minWidth={0}><Box display="flex" gap={1} alignItems="center"><Typography fontWeight={800} noWrap>{user.name}</Typography><Chip size="small" label={roles[user.role]||'Padrão'} color={user.role==='admin'?'primary':'default'}/></Box><Typography variant="caption" color="text.secondary" noWrap>{user.email} · {user.sector_name||'Setor não informado'}</Typography></Box>
   <FormControl size="small" sx={{display:{xs:'none',md:'inline-flex'}}} disabled={user.id===currentUser.id||!isAdmin&&['admin','gerente'].includes(user.role)}><InputLabel>Perfil</InputLabel><Select label="Perfil" value={['elaborador','revisor'].includes(user.role)?'padrao':user.role||'padrao'} onChange={e=>update(user.id,{role:e.target.value})}>{Object.entries(roles).filter(([value])=>isAdmin||!['admin','gerente'].includes(value)).map(([value,label])=><MenuItem key={value} value={value}>{label}</MenuItem>)}</Select></FormControl>
   <Box display={{xs:'none',md:'flex'}} alignItems="center"><Switch size="small" checked={user.active!==false} disabled={user.id===currentUser.id||!isAdmin&&['admin','gerente'].includes(user.role)} onChange={e=>update(user.id,{active:e.target.checked})}/><Typography variant="body2">{user.active!==false?'Ativo':'Inativo'}</Typography></Box>
   <Tooltip title="Trocar senha"><span><IconButton disabled={!isAdmin&&['admin','gerente'].includes(user.role)} onClick={()=>{setError('');setForm({...form,password:'',confirm:''});setDialog({type:'password',id:user.id,name:user.name})}}><Key/></IconButton></span></Tooltip>
   <Tooltip title={user.id===currentUser.id?'Conta atual protegida':'Desativar usuário'}><span><IconButton disabled={user.id===currentUser.id||!isAdmin&&['admin','gerente'].includes(user.role)} onClick={()=>remove(user.id)}><DeleteOutline/></IconButton></span></Tooltip>
  </Card>)}</Box>
  <Dialog open={dialog?.type==='new'} onClose={()=>setDialog(null)} fullWidth maxWidth="sm"><Box component="form" onSubmit={create}><DialogTitle>Novo usuário</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:'12px!important'}}>{error&&<Alert severity="error">{error}</Alert>}<TextField required label="Nome completo" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><TextField required label="E-mail institucional" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><FormControl required><InputLabel>Setor</InputLabel><Select label="Setor" value={form.sector} onChange={e=>setForm({...form,sector:e.target.value})}>{sectorOptions.map(s=><MenuItem key={s.id} value={s.name}>{s.name}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>Tipo de usuário</InputLabel><Select label="Tipo de usuário" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{Object.entries(roles).filter(([value])=>isAdmin||!['admin','gerente'].includes(value)).map(([value,label])=><MenuItem key={value} value={value}>{label}</MenuItem>)}</Select></FormControl><TextField required type="password" label="Senha forte" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><TextField required type="password" label="Confirmar senha" value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/></DialogContent><DialogActions><Button onClick={()=>setDialog(null)}>Cancelar</Button><Button type="submit" variant="contained">Criar usuário</Button></DialogActions></Box></Dialog>
  <Dialog open={dialog?.type==='password'} onClose={()=>setDialog(null)} fullWidth maxWidth="xs"><Box component="form" onSubmit={changePassword}><DialogTitle>Trocar senha — {dialog?.name}</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:'12px!important'}}>{error&&<Alert severity="error">{error}</Alert>}<TextField required type="password" label="Nova senha forte" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} helperText="8+ caracteres, maiúscula, minúscula, número e símbolo"/><TextField required type="password" label="Confirmar senha" value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/></DialogContent><DialogActions><Button onClick={()=>setDialog(null)}>Cancelar</Button><Button type="submit" variant="contained">Alterar senha</Button></DialogActions></Box></Dialog>
  </Box>
 </Box>
}
